template_variables:
  project_name:
    description: 'Name of your project (will be used for the main folder and commands)'
    required: true
    default: 'MyProject'
  author_name:
    description: 'Your name (will be added to pyproject.toml)'
    required: true
  author_email:
    description: 'Your email (will be added to pyproject.toml)'
    required: true
