name: Template Setup
on:
  create:
    branches: [ main ]

jobs:
  setup:
    runs-on: ubuntu-latest
    if: github.event.repository.is_template == false
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'
          
      - name: Run template setup
        env:
          TEMPLATE_PROJECT_NAME: ${{ github.event.repository.name }}
        run: python scripts/post_template_setup.py
        
      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Initialize template with project configuration"
          git push
